### ISSUE TITLE
r-tmap import issues in fresh environment 

### ISSUE THREAD

**Issue by spittssj** [conda-forge/r-tmap-feedstock#10]
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

tmap does not import correctly in a fresh environment.

# Creating the Environment #
<details>
<pre>
stephenpitts@Ellacuria envs % conda create -n tmap-test r-base r-tmap      
Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/stephenpitts/miniconda3/envs/tmap-test

  added / updated specs:
    - r-base
    - r-tmap
</pre>
</details>

# Importing tmap
<pre>
stephenpitts@Ellacuria envs % conda activate tmap-test
(tmap-test) stephenpitts@Ellacuria envs % R

R version 4.0.3 (2020-10-10) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library("tmap")
Error: package or namespace load failed for ‘tmap’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/Users/stephenpitts/miniconda3/envs/tmap-test/lib/R/library/lwgeom/libs/lwgeom.dylib':
  dlopen(/Users/stephenpitts/miniconda3/envs/tmap-test/lib/R/library/lwgeom/libs/lwgeom.dylib, 6): Library not loaded: @rpath/libproj.15.dylib
  Referenced from: /Users/stephenpitts/miniconda3/envs/tmap-test/lib/R/library/lwgeom/libs/lwgeom.dylib
  Reason: image not found
> ng environment: done
Error: unexpected symbol in "ng environment"

</pre>
<br/>
Environment (<code>conda list</code>):
<details>
<pre>
# packages in environment at /Users/stephenpitts/miniconda3/envs/tmap-test:
#
# Name                    Version                   Build  Channel
_r-mutex                  1.0.1               anacondar_1    conda-forge
boost-cpp                 1.74.0               h43a636a_2    conda-forge
bwidget                   1.9.14               h694c41f_0    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cairo                     1.16.0            h4ec454a_1007    conda-forge
cctools_osx-64            949.0.1             h2f0f38f_19    conda-forge
cfitsio                   3.470                h01dc385_7    conda-forge
clang                     11.0.1               h694c41f_1    conda-forge
clang-11                  11.0.1          default_hf8bb9ca_1    conda-forge
clang_osx-64              11.0.1               hb91bd55_0    conda-forge
clangxx                   11.0.1          default_hf8bb9ca_1    conda-forge
clangxx_osx-64            11.0.1               h7e1b574_0    conda-forge
compiler-rt               11.0.1               h654b07c_0    conda-forge
compiler-rt_osx-64        11.0.1               h8c5fa43_0    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
expat                     2.2.9                h046ec9c_3    conda-forge
fontconfig                2.13.1            hd23ceaa_1004    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
freexl                    1.0.5             h0b31af3_1002    conda-forge
fribidi                   1.0.10               hbcb3906_0    conda-forge
geos                      3.8.1                h4a8c4bd_0    conda-forge
geotiff                   1.6.0                hc1004f4_3    conda-forge
gettext                   0.19.8.1          h7937167_1005    conda-forge
gfortran_impl_osx-64      9.3.0               h8668ab3_17    conda-forge
gfortran_osx-64           9.3.0               h0d18d9c_12    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
gmp                       6.2.1                h2e338ed_0    conda-forge
graphite2                 1.3.13            h2e338ed_1001    conda-forge
gsl                       2.6                  h71c5fe9_2    conda-forge
harfbuzz                  2.7.4                hf28d55f_0    conda-forge
hdf4                      4.2.13            h71d84a9_1004    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
isl                       0.22.1               hb1e8313_2    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
json-c                    0.13.1            h575e443_1002    conda-forge
kealib                    1.4.14               h82515a5_0    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
ld64_osx-64               530                 hea264c1_19    conda-forge
ldid                      2.1.2                h7660a38_2    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libclang-cpp11            11.0.1          default_hf8bb9ca_1    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.1               habf9029_0    conda-forge
libdap4                   3.20.6               h993cace_1    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgdal                   3.1.4                hbb49e5d_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_17    conda-forge
libgfortran-devel_osx-64  9.3.0               h6c81a4c_17    conda-forge
libgfortran5              9.3.0               h6c81a4c_17    conda-forge
libglib                   2.66.4               h7424822_2    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
libkml                    1.3.0             h8ca2c65_1012    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm11                 11.0.1               h223d4b2_0    conda-forge
libnetcdf                 4.7.4           nompi_h9d8a93f_107    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libpq                     12.3                 h7049927_3    conda-forge
libspatialite             5.0.0                h1d49f08_0    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
llvm-openmp               11.0.1               h7c73e74_0    conda-forge
llvm-tools                11.0.1               h223d4b2_0    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
make                      4.3                  h22f3db7_1    conda-forge
mpc                       1.1.0             ha57cd0f_1009    conda-forge
mpfr                      4.0.2                h72d8aaf_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
pango                     1.42.4               ha86e081_5    conda-forge
pcre                      8.44                 hb1e8313_0    conda-forge
pcre2                     10.36                h91abf9c_0    conda-forge
pixman                    0.40.0               hbcb3906_0    conda-forge
poppler                   0.89.0               hd735947_5    conda-forge
poppler-data              0.4.10                        0    conda-forge
postgresql                12.3                 he852019_3    conda-forge
proj                      7.1.1                h45baca5_3    conda-forge
r-abind                   1.4_5           r40h6115d3f_1003    conda-forge
r-assertthat              0.2.1             r40h6115d3f_2    conda-forge
r-backports               1.2.1             r40h066c5db_0    conda-forge
r-base                    4.0.3                h2b2b636_5    conda-forge
r-base64enc               0.1_3           r40h17f1fa6_1004    conda-forge
r-brio                    1.1.1             r40h066c5db_0    conda-forge
r-bslib                   0.2.4             r40hc72bb7e_0    conda-forge
r-cachem                  1.0.1             r40h066c5db_0    conda-forge
r-callr                   3.5.1             r40h142f84f_0    conda-forge
r-class                   7.3_18            r40h066c5db_0    conda-forge
r-classint                0.4_3             r40h43cf36c_2    conda-forge
r-cli                     2.2.0             r40hc72bb7e_0    conda-forge
r-colorspace              2.0_0             r40h6b199c2_0    conda-forge
r-colourvalues            0.3.7             r40h815b84a_0    conda-forge
r-commonmark              1.7             r40h17f1fa6_1002    conda-forge
r-crayon                  1.3.4           r40h6115d3f_1003    conda-forge
r-crosstalk               1.1.1             r40hc72bb7e_0    conda-forge
r-dbi                     1.1.1             r40hc72bb7e_0    conda-forge
r-desc                    1.2.0           r40h6115d3f_1003    conda-forge
r-dichromat               2.0_0                  r40_2002    conda-forge
r-diffobj                 0.3.3             r40h066c5db_0    conda-forge
r-digest                  0.6.27            r40h342fd00_0    conda-forge
r-e1071                   1.7_4             r40h342fd00_0    conda-forge
r-ellipsis                0.3.1             r40h17f1fa6_0    conda-forge
r-evaluate                0.14              r40h6115d3f_2    conda-forge
r-fansi                   0.4.2             r40h066c5db_0    conda-forge
r-farver                  2.0.3             r40hc5da6b9_1    conda-forge
r-fastmap                 1.1.0             r40h815b84a_0    conda-forge
r-fs                      1.5.0             r40h710217c_0    conda-forge
r-geojsonsf               2.0.1             r40h342fd00_0    conda-forge
r-geometries              0.2.0             r40h1019320_0    conda-forge
r-ggplot2                 3.3.3             r40hc72bb7e_0    conda-forge
r-glue                    1.4.2             r40h066c5db_0    conda-forge
r-googlepolylines         0.8.2             r40h815b84a_0    conda-forge
r-gridextra               2.3             r40h6115d3f_1003    conda-forge
r-gtable                  0.3.0             r40h6115d3f_3    conda-forge
r-htmltools               0.5.1.1           r40h815b84a_0    conda-forge
r-htmlwidgets             1.5.3             r40hc72bb7e_0    conda-forge
r-httpuv                  1.5.5             r40h815b84a_0    conda-forge
r-isoband                 0.2.3             r40h1019320_0    conda-forge
r-jquerylib               0.1.3             r40hc72bb7e_0    conda-forge
r-jsonify                 1.2.1             r40hc5da6b9_0    conda-forge
r-jsonlite                1.7.2             r40h066c5db_0    conda-forge
r-kernsmooth              2.23_18           r40h983bced_0    conda-forge
r-labeling                0.4.2             r40h142f84f_0    conda-forge
r-later                   1.1.0.1           r40hc5da6b9_0    conda-forge
r-lattice                 0.20_41           r40h066c5db_3    conda-forge
r-lazyeval                0.2.2             r40h17f1fa6_2    conda-forge
r-leafem                  0.1.3             r40h6115d3f_0    conda-forge
r-leaflet                 2.0.4.1           r40hc72bb7e_0    conda-forge
r-leaflet.providers       1.9.0             r40h6115d3f_1    conda-forge
r-leafsync                0.1.0             r40h6115d3f_1    conda-forge
r-lifecycle               0.2.0             r40h6115d3f_1    conda-forge
r-lwgeom                  0.1_7             r40hc5da6b9_2    conda-forge
r-magrittr                2.0.1             r40h066c5db_1    conda-forge
r-mapdeck                 0.3.4             r40h7d45411_1    conda-forge
r-markdown                1.1               r40h066c5db_1    conda-forge
r-mass                    7.3_53            r40h066c5db_0    conda-forge
r-matrix                  1.3_2             r40he51b063_0    conda-forge
r-mgcv                    1.8_33            r40hb6d66fe_0    conda-forge
r-mime                    0.9               r40h066c5db_1    conda-forge
r-munsell                 0.5.0           r40h6115d3f_1003    conda-forge
r-nlme                    3.1_151           r40h1a6e9bf_0    conda-forge
r-pillar                  1.4.7             r40hc72bb7e_0    conda-forge
r-pkgbuild                1.2.0             r40hc72bb7e_0    conda-forge
r-pkgconfig               2.0.3             r40h6115d3f_1    conda-forge
r-pkgload                 1.1.0             r40hc5da6b9_0    conda-forge
r-png                     0.1_7           r40h17f1fa6_1004    conda-forge
r-praise                  1.0.0           r40h6115d3f_1004    conda-forge
r-prettyunits             1.1.1             r40h6115d3f_1    conda-forge
r-processx                3.4.5             r40he27d7ee_0    conda-forge
r-promises                1.1.1             r40hc5da6b9_0    conda-forge
r-ps                      1.5.0             r40h066c5db_0    conda-forge
r-r6                      2.5.0             r40hc72bb7e_0    conda-forge
r-rapidjsonr              1.2.0             r40h6115d3f_1    conda-forge
r-rappdirs                0.3.2             r40hf6ff476_0    conda-forge
r-raster                  3.4_5             r40h7d45411_0    conda-forge
r-rcolorbrewer            1.1_2           r40h6115d3f_1003    conda-forge
r-rcpp                    1.0.6             r40h815b84a_0    conda-forge
r-rematch2                2.1.2             r40h6115d3f_1    conda-forge
r-rlang                   0.4.10            r40h066c5db_0    conda-forge
r-rprojroot               2.0.2             r40hc72bb7e_0    conda-forge
r-rstudioapi              0.13              r40hc72bb7e_0    conda-forge
r-sass                    0.3.1             r40h815b84a_0    conda-forge
r-scales                  1.1.1             r40h6115d3f_0    conda-forge
r-sf                      0.9_7             r40h935d032_0    conda-forge
r-sfheaders               0.4.0             r40h1019320_0    conda-forge
r-shiny                   1.6.0             r40hc72bb7e_0    conda-forge
r-sourcetools             0.1.7           r40h4a8c4bd_1002    conda-forge
r-sp                      1.4_5             r40h066c5db_0    conda-forge
r-spatialwidget           0.2.3             r40h710217c_0    conda-forge
r-stars                   0.4_1             r40h6115d3f_1    conda-forge
r-testthat                3.0.1             r40h815b84a_0    conda-forge
r-tibble                  3.0.5             r40h066c5db_0    conda-forge
r-tmap                    3.0               r40h6115d3f_1    conda-forge
r-tmaptools               3.0               r40h6115d3f_1    conda-forge
r-units                   0.6_7             r40hc5da6b9_0    conda-forge
r-utf8                    1.1.4           r40h17f1fa6_1003    conda-forge
r-vctrs                   0.3.6             r40h066c5db_0    conda-forge
r-viridis                 0.5.1           r40h6115d3f_1004    conda-forge
r-viridislite             0.3.0           r40h6115d3f_1003    conda-forge
r-waldo                   0.2.3             r40hc72bb7e_0    conda-forge
r-withr                   2.4.1             r40hc72bb7e_0    conda-forge
r-xfun                    0.20              r40h066c5db_0    conda-forge
r-xml                     3.99_0.5          r40h066c5db_0    conda-forge
r-xtable                  1.8_4             r40h6115d3f_3    conda-forge
r-yaml                    2.2.1             r40h066c5db_1    conda-forge
r-zeallot                 0.1.0           r40h6115d3f_1002    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
tapi                      1100.0.11            h9ce4665_0    conda-forge
tiledb                    2.1.6                h6a9efa5_1    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
tktable                   2.10                 h49f0cf7_3    conda-forge
tzcode                    2021a                h35c211d_0    conda-forge
udunits2                  2.2.27.27            h9371bac_0    conda-forge
xerces-c                  3.2.3                hd3a8c1e_2    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                hf387650_1    conda-forge
</pre>
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>
<pre>
     active environment : tmap-test
    active env location : /Users/stephenpitts/miniconda3/envs/tmap-test
            shell level : 1
       user config file : /Users/stephenpitts/.condarc
 populated config files : /Users/stephenpitts/.condarc
          conda version : 4.9.2
    conda-build version : not installed
         python version : 3.8.5.final.0
       virtual packages : __osx=10.16=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /Users/stephenpitts/miniconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/osx-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/osx-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /Users/stephenpitts/miniconda3/pkgs
                          /Users/stephenpitts/.conda/pkgs
       envs directories : /Users/stephenpitts/miniconda3/envs
                          /Users/stephenpitts/.conda/envs
               platform : osx-64
             user-agent : conda/4.9.2 requests/2.24.0 CPython/3.8.5 Darwin/20.2.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
</pre>

</details>

**Comment by izahn** [comment]
The problem stems from the fact the `lwgeom` conda package hasn't been updated in a while, and everything that depends on it is starting to break. I tried pinging the maintainers over at https://github.com/conda-forge/r-lwgeom-feedstock/issues/12, and will take a stab at updating it myself.

**Comment by spittssj** [comment]
Thanks for getting back to me, on all three of the issues I posted. I'm happy to help: I am a 1st year PhD student and hope to use R and GIS in more research as I progress.

**Comment by spittssj** [comment]
Now that we have resolved [this r-lwgeom issue](https://github.com/conda-forge/r-tmap-feedstock/issues/10), r-tmap has been fixed as well. I tried again to install `r-tmap` in a fresh environment and it worked fine.
